version: '3.8'

services:
  conexao-de-sorte-backend-scheduler:
    image: ghcr.io/wibson82/conexao-de-sorte-backend-scheduler:latest
    container_name: conexao-de-sorte-backend-scheduler
    
    # OTIMIZAÇÃO HOSTINGER KVM 2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400m
        reservations:
          cpus: '0.1'
          memory: 128m
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    
    # Configurações otimizadas
    restart: unless-stopped
    
    # Health check otimizado para Hostinger KVM 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 90s        # Aumentado de 60s
      timeout: 30s         # Aumentado de 10s
      retries: 5           # Aumentado de 3
      start_period: 180s   # Aumentado de 90s
    
    # Variáveis de ambiente JVM otimizadas
    environment:
      - JAVA_OPTS=-Xms64m -Xmx250m -XX:+UseG1GC -XX:MaxGCPauseMillis=300 -XX:+UseStringDeduplication -XX:+UseCompressedOops
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=prod
    
    # Secrets via Docker Swarm
    secrets:
      - conexao-de-sorte-database-password
      - conexao-de-sorte-redis-password
      - conexao-de-sorte-jwt-secret
    
    # Networks
    networks:
      - conexao-network-swarm
    
    # Logging otimizado
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Secrets externos
secrets:
  conexao-de-sorte-database-password:
    external: true
  conexao-de-sorte-redis-password:
    external: true
  conexao-de-sorte-jwt-secret:
    external: true

# Networks externos
networks:
  conexao-network-swarm:
    external: true
