
services:
  # ========================================
  # 🗓️ MICROSERVIÇO SCHEDULER (ETL/JOB)
  # ========================================
  scheduler-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler-microservice
    restart: "on-failure:10"  # Limita a 10 tentativas de restart
    ports:
      - "8084:8084"
    environment:
      # Azure Key Vault Configuration
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_KEYVAULT_ENDPOINT=${AZURE_KEYVAULT_ENDPOINT}

      # Spring Profile
      - SPRING_PROFILES_ACTIVE=container

      # Database Configuration (Docker Secrets + Azure Key Vault fallback)
      # Conecta ao MySQL da infraestrutura compartilhada
      - DATABASE_R2DBC_URL=${DATABASE_R2DBC_URL:-r2dbc:mysql://conexao-mysql:3306/conexao_sorte_scheduler}
      - DATABASE_JDBC_URL=${DATABASE_JDBC_URL:-jdbc:mysql://conexao-mysql:3306/conexao_sorte_scheduler}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-}

      # Fallback para Key Vault (compatibilidade)
      - conexao-de-sorte-database-r2dbc-url=${conexao-de-sorte-database-r2dbc-url:-r2dbc:mysql://conexao-mysql:3306/conexao_sorte_scheduler}
      - conexao-de-sorte-database-jdbc-url=${conexao-de-sorte-database-jdbc-url:-jdbc:mysql://conexao-mysql:3306/conexao_sorte_scheduler}
      - conexao-de-sorte-database-username=${conexao-de-sorte-database-username:-}
      - conexao-de-sorte-database-password=${conexao-de-sorte-database-password:-}

      # Redis Configuration (Docker Secrets + Azure Key Vault fallback)
      # Conecta ao Redis da infraestrutura compartilhada
      - REDIS_HOST=${REDIS_HOST:-conexao-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DATABASE=${REDIS_DATABASE:-3}

      # Fallback para Key Vault (compatibilidade)
      - conexao-de-sorte-redis-host=${conexao-de-sorte-redis-host:-conexao-redis}
      - conexao-de-sorte-redis-port=${conexao-de-sorte-redis-port:-6379}
      - conexao-de-sorte-redis-password=${conexao-de-sorte-redis-password:-}
      - conexao-de-sorte-redis-database=${conexao-de-sorte-redis-database:-3}

      # JWT Configuration (Docker Secrets + Azure Key Vault fallback)
      - JWT_ISSUER=${JWT_ISSUER:-https://auth.conexaodesorte.com}
      - JWT_JWKS_URI=${JWT_JWKS_URI:-https://auth.conexaodesorte.com/.well-known/jwks.json}

      # Fallback para Key Vault (compatibilidade)
      - conexao-de-sorte-jwt-issuer=${conexao-de-sorte-jwt-issuer:-https://auth.conexaodesorte.com}
      - conexao-de-sorte-jwt-jwks-uri=${conexao-de-sorte-jwt-jwks-uri:-https://auth.conexaodesorte.com/.well-known/jwks.json}

      # CORS Configuration (Docker Secrets + Azure Key Vault fallback)
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS:-true}

      # Fallback para Key Vault (compatibilidade)
      - conexao-de-sorte-cors-allowed-origins=${conexao-de-sorte-cors-allowed-origins:-*}
      - conexao-de-sorte-cors-allow-credentials=${conexao-de-sorte-cors-allow-credentials:-true}

      # SSL Configuration (Docker Secrets + Azure Key Vault fallback)
      - SSL_ENABLED=${SSL_ENABLED:-false}

      # Fallback para Key Vault (compatibilidade)
      - conexao-de-sorte-ssl-enabled=${conexao-de-sorte-ssl-enabled:-false}

      # Logging
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_CONEXAODESORTE=DEBUG
    # Conecta aos serviços da infraestrutura-core (externos)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 10  # Limita a 10 tentativas de healthcheck
      start_period: 60s
    networks:
      - conexao-network-swarm
    volumes:
      - ./logs:/app/logs

  # ========================================
  # 📋 OBSERVAÇÃO: MySQL e Redis fornecidos pela infraestrutura-core
  # ========================================
  # O MySQL e Redis são gerenciados pelo projeto infraestrutura-core
  # Este microserviço conecta aos serviços compartilhados:

# ========================================
# 💾 VOLUMES PERSISTENTES
# ========================================
# Volumes removidos: MySQL próprio foi eliminado
# Usa infraestrutura compartilhada via conexao-network-swarm

# ========================================
# 🌐 REDE EXTERNA (CONEXÃO COM OUTROS MICROSERVIÇOS)
# ========================================
networks:
  conexao-network-swarm:
    name: conexao-network-swarm
    external: true
