
services:
  # ========================================
  # 🗓️ MICROSERVIÇO SCHEDULER (ETL/JOB)
  # ========================================
  scheduler:
    image: ghcr.io/wibson82/conexao-de-sorte-backend-scheduler:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SCHEDULER_LOG_LEVEL=INFO
      - LOGGING_LEVEL_ROOT=INFO
    secrets:
      - conexao-de-sorte-database-r2dbc-url
      - conexao-de-sorte-database-username
      - conexao-de-sorte-database-password
      - conexao-de-sorte-redis-host
      - conexao-de-sorte-redis-port
      - conexao-de-sorte-redis-password
      - conexao-de-sorte-redis-database
      - conexao-de-sorte-jwt-issuer
      - conexao-de-sorte-jwt-jwks-uri
      - conexao-de-sorte-server-port
    networks:
      - conexao-network-swarm
    volumes:
      - scheduler-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

    # ==========================================================================
    # 🏷️ TRAEFIK LABELS - SCHEDULER HEALTH MONITORING
    # ==========================================================================
    labels:
      # Habilitar Traefik para este serviço
      - "traefik.enable=true"
      - "traefik.docker.network=conexao-network-swarm"

      # Configuração do serviço Scheduler
      - "traefik.http.services.scheduler-service.loadbalancer.server.port=8085"
      - "traefik.http.services.scheduler-service.loadbalancer.healthcheck.path=/actuator/health"
      - "traefik.http.services.scheduler-service.loadbalancer.healthcheck.interval=30s"

      # Health check individual do Scheduler
      - "traefik.http.routers.scheduler-health.rule=Host(`traefik.conexaodesorte.com.br`) && PathPrefix(`/health/service/scheduler`)"
      - "traefik.http.routers.scheduler-health.entrypoints=websecure"
      - "traefik.http.routers.scheduler-health.tls.certresolver=letsencrypt"
      - "traefik.http.routers.scheduler-health.service=scheduler-service"
      - "traefik.http.routers.scheduler-health.middlewares=scheduler-health-rewrite"

      # Middleware para reescrever path do health check
      - "traefik.http.middlewares.scheduler-health-rewrite.replacepath.path=/actuator/health"

      # Metadata do serviço
      - "org.opencontainers.image.title=Conexão de Sorte - Scheduler"
      - "org.opencontainers.image.description=Microserviço de agendamento e processamento ETL"
      - "org.opencontainers.image.version=1.0.0"
      - "microservice.type=scheduler"
      - "microservice.category=etl"

  # ========================================
  # 📋 OBSERVAÇÃO: MySQL e Redis fornecidos pela infraestrutura-core
  # ========================================
  # O MySQL e Redis são gerenciados pelo projeto infraestrutura-core
  # Este microserviço conecta aos serviços compartilhados:

# ========================================
# 💾 VOLUMES PERSISTENTES
# ========================================
# Volumes removidos: MySQL próprio foi eliminado
# Usa infraestrutura compartilhada via conexao-network-swarm

# ========================================
# 🌐 REDE EXTERNA (CONEXÃO COM OUTROS MICROSERVIÇOS)
# ========================================
networks:
  conexao-network-swarm:
    name: conexao-network-swarm
    external: true

volumes:
  scheduler-logs:

secrets:
  conexao-de-sorte-database-r2dbc-url:
    external: true
  conexao-de-sorte-database-username:
    external: true
  conexao-de-sorte-database-password:
    external: true
  conexao-de-sorte-redis-host:
    external: true
  conexao-de-sorte-redis-port:
    external: true
  conexao-de-sorte-redis-password:
    external: true
  conexao-de-sorte-redis-database:
    external: true
  conexao-de-sorte-jwt-issuer:
    external: true
  conexao-de-sorte-jwt-jwks-uri:
    external: true
  conexao-de-sorte-server-port:
    external: true
