# =======================================================================
# 📅 Scheduler - Container Configuration Profile
# =======================================================================
# Profile específico para execução em container com docker-compose
# =======================================================================

spring:
  # Database Configuration for Container - Padrão híbrido
  r2dbc:
    url: ${DATABASE_R2DBC_URL:${conexao-de-sorte-database-r2dbc-url:r2dbc:mysql://scheduler-mysql:3306/conexao_sorte_scheduler?useSSL=false&allowPublicKeyRetrieval=true}}
    username: ${DATABASE_USERNAME:${conexao-de-sorte-database-username:scheduler_user}}
    password: ${DATABASE_PASSWORD:${conexao-de-sorte-database-password:scheduler_pass123!}}
    properties:
      prepStmtCacheSize: 200
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

  # Flyway configuration for migrations - Padrão híbrido
  flyway:
    url: ${DATABASE_JDBC_URL:${conexao-de-sorte-database-jdbc-url:jdbc:mysql://scheduler-mysql:3306/conexao_sorte_scheduler?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}}
    user: ${DATABASE_USERNAME:${conexao-de-sorte-database-username:scheduler_user}}
    password: ${DATABASE_PASSWORD:${conexao-de-sorte-database-password:scheduler_pass123!}}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

  # Redis Configuration for Container - Padrão híbrido
  data:
    redis:
      host: ${REDIS_HOST:${conexao-de-sorte-redis-host:redis}}
      port: ${REDIS_PORT:${conexao-de-sorte-redis-port:6379}}
      password: ${REDIS_PASSWORD:${conexao-de-sorte-redis-password:}}
      database: ${REDIS_DATABASE:${conexao-de-sorte-redis-database:3}}
      timeout: 3000ms

  # Security Configuration - Padrão híbrido
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:${conexao-de-sorte-jwt-issuer:https://auth.conexaodesorte.com}}
          jwk-set-uri: ${JWT_JWKS_URI:${conexao-de-sorte-jwt-jwks-uri:https://auth.conexaodesorte.com/.well-known/jwks.json}}

  # Azure Key Vault disabled for container
  cloud:
    azure:
      keyvault:
        secret:
          enabled: false

# Server configuration
server:
  port: 8084

# Logging for Container
logging:
  level:
    root: INFO
    "[br.tec.facilitaservicos]": DEBUG
    "[org.springframework.r2dbc]": DEBUG

# Scheduler configuration
scheduler:
  etl:
    loterias:
      enabled: true
      backoff-ms: 2000
      max-retries: 5
      modalidades:
        - megasena
        - quina
        - lotofacil
        - lotomania
        - duplasena
        - timemania
        - diadesorte
        - supersete
        - loteca
        - milionaria